### ISSUE TITLE
Installing on 32 bit python

### ISSUE THREAD

**Issue by tdowrick** [UCL/scikit-surgerynditracker#45]
Failed installation when trying to install on 32-bit python, to be able to work alongside the Ultrasonix library:
```
    ERROR: Command errored out with exit status 1:
     command: 'c:\program files (x86)\python37-32\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Tom\\AppData\\Local\\Temp\\pip-install-pp7tbbtp\\ndicapi\\setup.py'"'"'; __file__='"'"'C:\\Users\\Tom\\AppData\\Local\\Temp\\pip-install-pp7tbbtp\\ndicapi\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\Tom\AppData\Local\Temp\pip-pip-egg-info-y2asrywh'
         cwd: C:\Users\Tom\AppData\Local\Temp\pip-install-pp7tbbtp\ndicapi\
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Tom\AppData\Local\Temp\pip-install-pp7tbbtp\ndicapi\setup.py", line 10, in <module>
        long_description = io.open('README.pypi.md', encoding="utf-8").read()
    FileNotFoundError: [Errno 2] No such file or directory: 'README.pypi.md'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by thompson318** [comment]
We're using pre-built binaries of ndicapi. I suspect there isn't a pre-built binary for you're platform. The binaries are built with the with a github action here ... [https://github.com/thompson318/ndicapi/blob/2github-actions/.github/workflows/ci.yml](https://github.com/thompson318/ndicapi/blob/2github-actions/.github/workflows/ci.yml).
If you can tell me what platform and flags to use I can add them to the script and give it a try.

**Comment by tdowrick** [comment]
Build flags should be the same, so it is just the platform to change to Win32. I think the below should work:
```

      - name: build Windows-32bit
        if: matrix.os == 'windows-latest'
        run: |
          mkdir build
          mkdir install
          cd build
          cmake -G "Visual Studio 14 Win32" -DBUILD_PYTHON:BOOL=ON -DBUILD_SHARED_LIBS:BOOL=ON  -Dndicapi_BUILD_APPLICATIONS:BOOL=OFF -DCMAKE_INSTALL_PREFIX=../install ..
          cmake --build . 
          cd ../
          python.exe setup.py sdist bdist_wheel --plat-name win32
          python -m twine upload -u __token__ -p ${{secrets.PYPI_API_TOKEN}} dist/* --skip-existing
```

**Comment by thompson318** [comment]
OK, that seemed to work. There are now 32 bit builds for python 3.[6,7,8] on PyPi. Can you please try running it again?

**Comment by tdowrick** [comment]
Yes, can confirm it works, thanks!
